### PR TITLE
Created Minimap and Settings For Them

### PR DESCRIPTION
**Pull request by IsaGoodFriend**
Added a minimap to the collab settings.  You can enable and disable them in the meny, and bind a button to open a larger map to see more of the map.

### CODE REVIEW

**Comment by coloursofnoise** [comment]
@IsaGoodFriend the diff for [InGameOverworldHelper.cs](https://github.com/EverestAPI/CelesteCollabUtils2/pull/51/files?file-filters%5B%5D=.cs#diff-10c0a2d63c73a561d3f41305f396130dcbe43e20537052e5c3078b8efdf42a4b) is very big and seems that it may have been caused by accepting the Visual Studio prompt to "Normalize line endings". In the interest of making reviews easier it would be great if you could recreate your changes in the file without the line ending change, and normalize line endings in a separate commit if that's still needed.

**Comment by maddie480** [comment]
hm, I guess I can make a diff on my end, because it's indeed a mess and fixing it up isn't a bad thing 😅 

image

**Comment by maddie480** [comment]
the line ending conversion created conflicts though 😅

**Comment by maddie480** [comment]
I'm getting pretty big loading times when entering lobbies, those are not here in the released version, so this will be something that needs to be looked into before merging 🤔 

https://user-images.githubusercontent.com/52103563/128614273-ec39d682-69b2-4492-bbf7-fa6756f9fa5e.mp4

**Comment by IsaGoodFriend** [comment]
Yeah, I've noticed that.  I'm not sure if I'm able to modify/add to this PR or if I should just make a new one.
Also, sorry about all the line changes, Visual Studio changed them when I opened the files and I couldn't change them back 😅

**Comment by maddie480** [comment]
You can add to the pull request by pushing more commits to your fork :smile:

Some feedback I got from discussing the idea on the Strawberry Jam server:
- there should be a way to toggle the map, in case some collabs don't want it, and optionally have it unlock only after beating X maps. I was thinking of a meta.yaml attribute, and I'm not too sure whether it should be enabled or disabled by default (disabled would be the least breaking though). 🤔 For example:
```yaml
# Allow the player to use the minimap
CollabUtils2MiniMap: 
  Enabled: true

# Allow the player to use the minimap, but only after beating 5 maps
CollabUtils2MiniMap: 
  Enabled: true
  OnlyAfterBeating: 5
```
- the option should be disabled by default (which is already the case iirc) and keys unbound by default, to make the minimap fully opt-in

Those options aim to try to find the balance between people wanting the minimap (I personally want it :p) / fixing the "where is the last map of that lobby :a:" problem, and people who don't want the exploration part to be lost because players would just turn on the minimap instead... and since I don't want to take a decision for all collabs and contests out there, options sound like the way to go. 😅 

- also have a shape with the color, for colorblind people. For example:
image

I'll probably poll the Celeste Discord as well (like, to try and determine if the map should be on or off by default) before this is merged. 😅

**Comment by maddie480** [comment]
Closing since collab utils now has another lobby warp/map system 😅

**Pull request closed without merging**
