### PR TITLE
Chinese Translation

### PR DESCRIPTION
**Pull request by BLimmie**

### CODE REVIEW

**Comment by maddie480** [comment]
Seems like you have missing characters, use [that tool](https://max480-random-stuff.appspot.com/celeste/font-generator) to generate them

For instance, after "IL" in that message:
image

One character is missing: 需被用于认证在speedrun.com上的IL**申**请

**Review by maddie480 — CHANGES_REQUESTED** [review]
See comment

**Comment by WEGFan** [comment]
> modoptions_collab_displayendscreenforallmaps_description= 需被用于认证在speedrun.com上的IL申请

Will it be better if this is translated into `需被用于审核在 speedrun.com 上的单关记录提交`?

**Comment by WEGFan** [comment]
Fixed.

**Review by maddie480 — APPROVED** [review]

**Pull request merged**
